export https_proxy=...
export http_proxy=...
export all_proxy=...
docker_user=...

docker build --network host --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --build-arg all_proxy=$all_proxy -t pixiu:$(date +%Y%m%d) -f DOCKERFILE .
docker tag pixiu:$(date +%Y%m%d) $docker_user/pixiu:$(date +%Y%m%d)
docker push $docker_user/pixiu:$(date +%Y%m%d)