export https_proxy=...
export http_proxy=...
export all_proxy=...
docker_user=...

docker build --network host --build-arg HTTP_PROXY=$http_proxy -t pixiu:$(date +%Y%m%d) -f DOCKERFILE .
docker tag pixiu:$(date +%Y%m%d) $docker_user/pixiu:$(date +%Y%m%d)
docker push $docker_user/pixiu:$(date +%Y%m%d)